### ISSUE TITLE
Depricate ruby-sass

### ISSUE THREAD

**Issue by DanGould** [citizensgov/citizensgov2020#6]
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811

**Comment by rancerun** [comment]
thanks for finding this. sassc-rails is probably the way to go since it wraps sassc into the rails asset pipeline, and i'll give it a shot unless you have other suggestions
